Debugging error in the hugo build
```source "/pipeline/hugo-build-75d29379-78b0-4604-a45a-0e8164e9d05a/run.sh" < /dev/null
Cleaning the public directory
Running the Hugo command
/pipeline/hugo-build-75d29379-78b0-4604-a45a-0e8164e9d05a/bin/hugo_0.58.3 --source=/pipeline/source/ --buildDrafts=true
Building sites … Total in 21 ms
Error: Error building site: open /pipeline/source/public/empty.txt: no such file or directory```

This would mean that the dir is empty because it's gulp who generates it.